export {
  ALPHANUMERIC_PATTERN_REGEX,
  IS_MANUAL_CASE_REGEX,
  NO_CASE_SPLIT_REGEXP,
  NO_CASE_STRIP_REGEXP,
} from './case'

export {
  HTML_COMMENT_REGEX,
  HTML_LINE_BREAK_REGEX,
  HTML_NEWLINE_PARAGRAPHS_REGEX,
  HTML_TAG_REGEX,
} from './html'

export {
  MAGIC_SPLIT_REGEX,
  SPACE_SPLIT_REGEX,
  TOKENS_REGEX,
  WHITESPACE_REGEX,
} from './split'

export { DOUBLE_LINE_BREAK_REGEX, SMALL_WORDS_REGEX } from './text'

export { DURATION_WITH_UNIT_REGEX } from './unit'
