export type {
  CaseOptions,
  ExcerptOptions,
  PrettyDuration,
  SentenceOptions,
  Slugify,
  SlugifyOptions,
  TruncateOptions,
} from './modules/string'

export {
  default as string,
  capitalize,
  excerpt,
  fromMilliseconds,
  fromSeconds,
  interpolate,
  random,
  sentence,
  slug,
  truncate,
  toAdaCase,
  toCamelCase,
  toCapitalCase,
  toCobolCase,
  toConstantCase,
  toDotNotationCase,
  toKebabCase,
  toLowerCaseCase,
  toMilliseconds,
  toNoCase,
  toPascalCase,
  toPathCase,
  toSeconds,
  toSentenceCase,
  toSnakeCase,
  toSpaceCase,
  toTitleCase,
  toTrainCase,
  toUpperCase,
} from './modules/string'
