name: 🚀 Publish

on:
    workflow_dispatch:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: 🚀 Release
        runs-on: ubuntu-latest
        steps:
            - name: ⬇ Checkout
              uses: actions/checkout@v4

            - name: 🟢 Setup bun
              uses: oven-sh/setup-bun@v1

            - name: 🧩 Install Dependencies
              run: bun install

            - name: ⚡ Run tests
              run: bun test

            - name: 🏗 Build
              run: bun run build

            - name: 📣 Handle version release (PR or npm publish)
              uses: changesets/action@v1
              with:
                  title: "chore(release): version packages"
                  publish: bun run publish
                  version: bun run version
                  commit: "chore(release): version packages [skip ci]"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}